version: '3'

services:

    webservergo:
        container_name: app
        build: 
            context: .
            dockerfile: dockerfile
        ports: 
            - ${SERVER_PORT}:5000
        depends_on:
            - mysql

    dbeaver:
        image: dbeaver/cloudbeaver:latest
        container_name: dbeaver
        restart: unless-stopped
        tty: true
        ports:
            - "1000:8978"
        volumes:
            - cache:/opt/cloudbeaver/workspace

    mysql:

        image: mysql
        container_name: db
        ports: 
            - 3306:3306
        environment:       
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql

networks:
    default:  
        driver: bridge
        external: false
        name: crud-network 

volumes:    
    cache:
        driver: local

   